baseURL: "//bushuyeu.com/"
title: Pavel Bushuyeu
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-X74790T8FJ

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Pavel Bushuyeu
  description: "I write about products I like and projects I build."
  keywords: [Blog, Portfolio, Tech]
  author: Pavel Bushuyeu
  # author: ["Me", "You"] # multiple authors
  images: ["og.png"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # auto, dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: true
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: ""
    favicon16x16: ""
    favicon32x32: ""
    apple_touch_icon: ""
    safari_pinned_tab: ""

  label:
    text: "Pavel Bushuyeu"
    # icon: "images/apple-touch-icon.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hi there, I’m Pavel"
    subtitle: "I’m a product manager passionate about crafting digital products through discovery, prototyping and testing."
    imageUrl: "images/pb.png"
    imageWidth: 240
    imageHeight: 240
    imageTitle: "Pavel Bushuyeu"
    buttons:
      # - name: Blog
      #   url: blog
      - name: Projects
        url: projects

  # home-info mode
  homeInfoParams:
    Title: "Hi there, I’m Pavel"
    Content: "I’m a product manager passionate about crafting digital products through discovery, prototyping and testing."
  socialIcons:
    - name: email
      url: "mailto:p@bushuyeu.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/bushuyeu/"
    - name: github
      url: "https://github.com/bushuyeu"
    - name: telegram
      url: "https://t.me/bushuyeu"

  analytics:
    google:
      SiteVerificationTag: "GTM-K3BFMT3X"
    # bing:
    #   SiteVerificationTag: "XYZabc"
    # yandex:
    #   SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page

  editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" 
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    # - identifier: about
    #   name: About
    #   url: /about/
    #   weight: 10
    # - identifier: blog
    #   name: Blog
    #   url: /blog/
    #   weight: 20
    - name: Projects
      url: projects
      weight: 10
    # - identifier: resume
    #   name: Resume
    #   url: /resume/
    #   weight: 40

# pygmentsUseClasses: true 
# markup:
#   highlight:
#     noClasses: false
#     # anchorLineNos: true
#     # codeFences: true
#     # guessSyntax: true
#     # lineNos: true
#     # style: monokai